### ISSUE TITLE
Bug: Cannot add API resource

### ISSUE THREAD

**Issue by nigel-dewar** [joeaudette/cloudscribe#138]
Hi Joe,

Seems to be a bug here. All is well until one goes to add an API resource.

Try adding an API resource. You will get this error

An unhandled exception occurred while processing the request.

SqlException: The multi-part identifier "api.Id" could not be bound.
System.Data.SqlClient.SqlCommand+<>c.<ExecuteDbDataReaderAsync>b__107_0(Task<SqlDataReader> result)

The following may also help
cloudscribe.Core.IdentityServer.EFCore.Stores.ResourceStore+<FindApiResourcesByScopeAsync>d__5.MoveNext() in ResourceStore.cs
+
            var results = await apis.ToArrayAsync();
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

![image](https://cloud.githubusercontent.com/assets/9402456/24185715/6d772218-0f20-11e7-899a-c7c579c034f6.png)

Even if you are not asking for the api in your clients.

Please try and confirm.

**Comment by joeaudette** [comment]
maybe related to #131 which is fixed now. please see if you can still produce the problem and if so post steps to produce it

**Comment by nigel-dewar** [comment]
Hi Joe,

Issue still exists sorry. I pulled down FRESH clone of cloudscribe also just to make sure.

Steps to reproduce. 

1. Go to client mgt http://localhost:5000/clients 
Create a client . I have used js
![image](https://cloud.githubusercontent.com/assets/9402456/24319537/a373247e-116a-11e7-994d-a8b5f42bf984.png)

1.1 Set the following
![image](https://cloud.githubusercontent.com/assets/9402456/24319544/bfcbab28-116a-11e7-955a-71f1121215be.png)
and
![image](https://cloud.githubusercontent.com/assets/9402456/24319546/d1880834-116a-11e7-839a-962f47bfaa0b.png)
and
![image](https://cloud.githubusercontent.com/assets/9402456/24319548/db1e3b7a-116a-11e7-94fe-6c56ff502c9e.png)

2. Go to identity resource mgt http://localhost:5000/identityresource
Create 2 resources. openid and profile
![image](https://cloud.githubusercontent.com/assets/9402456/24319553/feefddc4-116a-11e7-8af2-500bfbae28e7.png)

2.1 openid looks like so
![image](https://cloud.githubusercontent.com/assets/9402456/24319555/12fa9674-116b-11e7-81dc-874645722cd1.png)

2.2 profile looks like so
![image](https://cloud.githubusercontent.com/assets/9402456/24319561/29e5543c-116b-11e7-9e95-aa606c4afb83.png)

3. Go to API resources http://localhost:5000/apiresource
Create an API resource called s1
![image](https://cloud.githubusercontent.com/assets/9402456/24319568/4b13021c-116b-11e7-9d62-21b1a8745174.png)

3.1 s1 looks like so
![image](https://cloud.githubusercontent.com/assets/9402456/24319571/59848140-116b-11e7-9b73-359b48f91005.png)
and
![image](https://cloud.githubusercontent.com/assets/9402456/24319573/628de27c-116b-11e7-8a03-ea5dd0a33714.png)

Make sure the js client has these allowed scopes
![image](https://cloud.githubusercontent.com/assets/9402456/24319578/798ba3ba-116b-11e7-9fba-5c174f95205c.png)

4. Go and edit the app.js in the wwwroot directory to test with a javascript client
change the config to look like so
var config = {
    authority: "http://localhost:5000",
    client_id: "js",
    redirect_uri: "http://localhost:5000/callback.html",
    response_type: "id_token token",
    scope:"openid profile s1",
    post_logout_redirect_uri: "http://localhost:5000/app.html",
};

with the api function also like
function api() {
    mgr.getUser().then(function (user) {
        var url = "http://localhost:5000/api/identity";

        var xhr = new XMLHttpRequest();
        xhr.open("GET", url);
        xhr.onload = function () {
            log(xhr.status, JSON.parse(xhr.responseText));
        }
        xhr.setRequestHeader("Authorization", "Bearer " + user.access_token);
        xhr.send();
    });
}

5. Visit http://localhost:5000/app.html
hit login
You will get this error
![image](https://cloud.githubusercontent.com/assets/9402456/24319585/ce2fcf0e-116b-11e7-9bd2-80936c5b4c5d.png)


6. If you remove the apiresource you will be ok
![image](https://cloud.githubusercontent.com/assets/9402456/24319587/f6085cda-116b-11e7-8b60-b9a7a922b595.png)

And ensure removed from cloudscribe backend
![image](https://cloud.githubusercontent.com/assets/9402456/24319589/0b147122-116c-11e7-867a-f96dab4d701e.png)
and client
![image](https://cloud.githubusercontent.com/assets/9402456/24319591/1827e722-116c-11e7-8747-fcaaf01b8578.png)

With apiresource removed, you have no issues

![image](https://cloud.githubusercontent.com/assets/9402456/24319600/547a7b22-116c-11e7-8aa8-21c96cf4a455.png)
and
![image](https://cloud.githubusercontent.com/assets/9402456/24319601/5e7068e4-116c-11e7-9503-ddaf9c457a52.png)
and call identityController
![image](https://cloud.githubusercontent.com/assets/9402456/24319605/705a71b2-116c-11e7-8a82-a005cb05321e.png)

Is there some special way one must setup the ApiResource Joe? cheers

Nige

**Comment by joeaudette** [comment]
are you using one of the starterkits or using the main code from the main repo?
did you start with a new clean database?

**Comment by nigel-dewar** [comment]
Hi Joe. Not using starterkit. Using main repo which i cloned fresh also. Using fresh new clean database also, i edited connection string to ensure this before firing it up first time.

**Comment by nigel-dewar** [comment]
I assume you must not be getting it.?

**Comment by joeaudette** [comment]
this app.html stuff in the main repo is just something I used to test a long time ago, it is not kept up to date and was not meant to be a sample. the starter kits are the samples that are intended to be kept up to date and working. the middleware for builder.UseIdentityServerAuthentication is commented out in Startup.cs so jwt is not even wired up to work right now, and it would only be using cookie auth without that.

nevertheless I will look into this.

**Comment by joeaudette** [comment]
thanks for reporting this, I was able to produce the error and fix it. should be fixed in the source solution and in the starterkits

**Comment by nigel-dewar** [comment]
Thanks Joe, appreciate this. Yes i remember you saying that the app files sitting in the main repo were just for testing. 

Cheers for fixing Joe.

**Comment by nigel-dewar** [comment]
Cheers Joe, confirmed this is fixed. Thank you again. Nige.
